<?php
/**
 * Beginning section is all data retrieval. 
 *  - I don't want to mix php logic with html so I want to gather all the data first before applying them to the view
 */
$status = Mage::getStoreConfig( 'rewardstream_options/section_one/rewardstream_status' );
$title_name = Mage::getStoreConfig( 'rewardstream_options/section_two/rewardstream_refer_title' );
$displayFirstPurchaseMessage = true;
$pageRefresh = false;

// If the user hasn't set the menu title name
if (empty($title_name)) {
    $title_name = "Refer A Friend";
}

// If the magento app enabled?
if ( $status == 1 ) { 
	if ( Mage::getSingleton( 'customer/session' )->isLoggedIn() ) {
		$customer = Mage::getSingleton( 'customer/session' )->getCustomer();
		$email = $customer->getEmail();
        $orderCollection = Mage::getModel( 'sales/order' )->getCollection()
            ->addFieldToFilter( 'customer_email', $email )
            ->addFieldToFilter( 'status', array('complete', 'processing') );
		$_orderCnt = $orderCollection->count();
        $first_purchase_required = Mage::getStoreConfig( 'rewardstream_options/section_two/rewardstream_first_purchase' );

        // Show referral platform?
        if ($first_purchase_required==2 || $_orderCnt > 0) {
            // Disable display of first purchase
            $displayFirstPurchaseMessage = false;
            
            $customerData = Mage::getSingleton( 'customer/session' )->getCustomer();
            $id = $customerData->getId();
            $apiUrl = 'https://' . Mage::getStoreConfig( 'rewardstream_options/section_one/rewardstream_api_url' );

            $apiKey = Mage::getStoreConfig( 'rewardstream_options/section_one/rewardstream_api_key' );
            $collection = Mage::getModel( 'rewardstream/rewardstream' )->load( $id, 'customer_id' );

            $customerid = $collection['customer_id'];
            $refreshTokenUrl = Mage::getUrl('rewardstream/index/refreshtoken');

            // Does the customer exist in our system already?
            if ( $customerid == $id ) {
                $accesstoken = $collection['access_token'];
                $rewardid = $collection['reward_id'];
                $activationtime = $collection['activationtime'];
                $expiretime = date( 'Y-m-d H:i:s', strtotime( '+2 hour', strtotime( $activationtime ) ) );
                $currenttime = date( 'Y-m-d H:i:s' );

                if ( isset( $accesstoken ) ) {
                    if ( $currenttime > $expiretime || $accesstoken == "" ) { 
                        // Need to call backend call to get token
                        $pageRefresh = true;
                    }
                }
            } else {
                // Need to call backend call to get token
                $pageRefresh = true;
            }
        }
	}
} else {
	$customerLoginURL = $this->getBaseUrl() . "customer/account/login";
	Mage::app()->getFrontController()->getResponse()->setRedirect( $customerLoginURL )->sendResponse();
} ?>

<!--Page Display-->
<div class="rewardstream-referafriend">
    <div class="page-title">
        <h1><?php echo $title_name;?></h1>
    </div>

    <div id="content-error" class="error"></div>
    <div class="loading"></div>

    <!--Display First Purchase Message-->
    <?php if ($displayFirstPurchaseMessage) { ?>
        <div class="before-purchase">
            <?php echo $this->getLayout()->createBlock( 'cms/block' )->setBlockId( 'refer-a-friend-purchase-required' )->toHtml(); ?>
        </div>

    <!--Display Embedded Referral Site-->
    <?php } else if (!$pageRefresh) { ?>
        <!--Load the page-->
        <div id="refer-a-friend-platform">
            <script type="text/javascript" src="<?php echo $apiUrl ?>/js/spark.v2.min.js?api_key=<?php echo $apiKey ?>&token=<?php echo $accesstoken ?>"></script>
            <?php echo $this->getLayout()->createBlock( 'cms/block' )->setBlockId( 'refer-a-friend-page-content' )->toHtml(); ?>
        </div>
    <?php } ?>

    <!--Loader and get the data-->
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var reward_id = "<?php echo $rewardid?>";
            var customer_id = "<?php echo $id?>";
            var refreshTokenUrl = "<?php echo $refreshTokenUrl;?>";
            var loaderUrl = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/rewardstream/loading.gif" ?>";
            var refreshPage = "<?php echo $pageRefresh?>";

            if (refreshPage) {
                RSUtility.refreshToken(reward_id, customer_id, refreshTokenUrl, "content-error", loaderUrl);
            }
        });
    </script>
</div>